name: build commits

on:
  push:
    branches-ignore: [ $default-branch ]
  pull_request: {}


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up jdk
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven
      - name: execute maven
        run: mvn -B install